name: gad_app_team
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.6.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  camera: ^0.10.5+2
  path_provider: ^2.1.1
  path: ^1.8.3
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.4.9
  uuid: ^4.3.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
      - assets/image/logo.png
      #- assets/image/anxiety_character.png
      #- assets/image/photo.png
      #- assets/image/ranking_illustration.png
      #- assets/image/otter_sushi.png
      #- assets/image/completion.png
      #- assets/image/weekly_diary.png
      #- assets/image/daily_diary.png 

      # 1주차 part1
      - assets/education_data/week1_part1_1.json
      - assets/education_data/week1_part1_2.json
      - assets/education_data/week1_part1_3.json
      - assets/education_data/week1_part1_4.json
      - assets/education_data/week1_part1_5.json
      - assets/education_data/week1_part1_6.json

      # 1주차 part2
      - assets/education_data/week1_part2_1.json
      - assets/education_data/week1_part2_2.json
      - assets/education_data/week1_part2_3.json

      # 1주차 part3
      - assets/education_data/week1_part3_1.json
      - assets/education_data/week1_part3_2.json
      - assets/education_data/week1_part3_3.json
      - assets/education_data/week1_part3_4.json
      - assets/education_data/week1_part3_5.json
      - assets/education_data/week1_part3_6.json
      - assets/education_data/week1_part3_7.json
      - assets/education_data/week1_part3_8.json
      - assets/education_data/week1_part3_9.json

      # 1주차 prat4
      - assets/education_data/week1_part4_1.json
      - assets/education_data/week1_part4_2.json
      - assets/education_data/week1_part4_3.json
      - assets/education_data/week1_part4_4.json
      - assets/education_data/week1_part4_5.json
      - assets/education_data/week1_part4_6.json

      # 1주차 part5
      - assets/education_data/week1_part5_1.json
      - assets/education_data/week1_part5_2.json
      - assets/education_data/week1_part5_3.json
      - assets/education_data/week1_part5_4.json
      - assets/education_data/week1_part5_5.json
      - assets/education_data/week1_part5_6.json
      - assets/education_data/week1_part5_7.json

      # 1주차 part6
      - assets/education_data/week1_part6_1.json
      - assets/education_data/week1_part6_2.json
      - assets/education_data/week1_part6_3.json
      - assets/education_data/week1_part6_4.json

flutter_native_splash:
  color: "#F9F5F9"
  image: assets/image/logo.png
  android: true
  ios: true
  fullscreen: true